"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent,useState } from "react";
import { AlertTriangle,BarChart3,Bell,Boxes,Building2,ChevronDown,CircleGauge,Download,PackageSearch,RefreshCw,Search,ShoppingCart,Sparkles,Store,X } from "lucide-react";
import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import type { DashboardData,Risk } from "@/lib/types";
import Sidebar from "./sidebar";
const riskClass=(risk:Risk)=>`risk risk-${risk.toLowerCase()}`;
const kpiRoutes=["/inventory","/orders","/demand","/inventory?risk=high","/inventory?risk=overstock","/analytics"];
export default function InteractiveDashboard({initialData}:{initialData:DashboardData}){
 const router=useRouter();const [data,setData]=useState(initialData),[refreshing,setRefreshing]=useState(false),[range,setRange]=useState("24H"),[store,setStore]=useState("All stores"),[storeOpen,setStoreOpen]=useState(false),[noticeOpen,setNoticeOpen]=useState(false),[statusOpen,setStatusOpen]=useState(false),[toast,setToast]=useState("");
 const showToast=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),2400)};
 async function refresh(){setRefreshing(true);try{const r=await fetch("/api/refresh",{method:"POST"});if(!r.ok)throw new Error();setData(await r.json());showToast("Intelligence refreshed successfully")}catch{showToast("Refresh failed. Please try again.")}finally{setRefreshing(false)}}
 function search(e:FormEvent<HTMLFormElement>){e.preventDefault();const q=new FormData(e.currentTarget).get("q")?.toString().trim();if(q)router.push(`/products?q=${encodeURIComponent(q)}`)}
 function exportCsv(){const rows=[["Product","SKU","Store","Stock","Predicted demand","Risk","Recommended reorder"],...data.risks.map(r=>[r.product,r.sku,r.store,r.stock,r.demand,r.risk,r.reorder])];const blob=new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="stocksense-risk-report.csv";a.click();URL.revokeObjectURL(url);showToast("Risk report exported")}
 return <div className="app-shell"><Sidebar/><main><header><div><span className="eyebrow">OPERATIONS COMMAND CENTER</span><h1>Good morning, Aarav.</h1><p>Here’s what needs your attention across the network.</p></div><div className="header-actions"><form className="search" onSubmit={search}><button type="submit" aria-label="Submit search"><Search size={17}/></button><input name="q" aria-label="Search" placeholder="Search products, stores..."/><kbd>↵</kbd></form><div className="popover-wrap"><button className="icon-btn" aria-label="Notifications" onClick={()=>setNoticeOpen(!noticeOpen)}><Bell size={19}/><i/></button>{noticeOpen?<div className="popover notifications"><strong>Notifications</strong>{data.alerts.map(a=><Link href="/alerts" key={a.title}><span>{a.title}</span><small>{a.time}</small></Link>)}<Link href="/alerts" className="popover-all">View all alerts →</Link></div>:null}</div><button className="export" onClick={exportCsv}><Download size={17}/> Export</button></div></header>
 <section className="controlbar"><button className="live live-button" onClick={()=>setStatusOpen(true)}><i/> LIVE INTELLIGENCE <span>Updated {refreshing?"refreshing…":"just now"}</span></button><div><div className="popover-wrap"><button className="selector" onClick={()=>setStoreOpen(!storeOpen)}><Building2 size={16}/> {store} <ChevronDown size={15}/></button>{storeOpen?<div className="popover stores-menu">{["All stores",...data.stores.map(s=>s.name)].map(name=><button key={name} onClick={()=>{setStore(name);setStoreOpen(false);showToast(`${name} filter applied`)}}>{name}</button>)}</div>:null}</div><button className="refresh" onClick={refresh} disabled={refreshing}><RefreshCw size={16} className={refreshing?"spin":""}/>{refreshing?"Refreshing…":"Refresh data"}</button></div></section>
 <section className="intelligence"><div className="intelligence-title"><span><Sparkles size={18}/>TODAY’S INTELLIGENCE</span><small>AI-assisted operational summary</small></div><div className="insight-grid">{data.insights.map((x,i)=><Link href={["/demand","/inventory?risk=high","/stores","/analytics"][i]} key={x}><b>{i+1}</b><p>{x}</p></Link>)}</div></section>
 <section className="kpis">{data.kpis.map((k,i)=><Link href={kpiRoutes[i]} className="kpi-link" key={k.label}><article><div className={`kpi-icon ${k.tone}`}>{[Boxes,ShoppingCart,BarChart3,AlertTriangle,PackageSearch,CircleGauge].map((Icon,j)=>j===i?<Icon key={j} size={20}/>:null)}</div><p>{k.label}</p><h2>{k.value}</h2><span className={k.tone}>{k.delta}</span></article></Link>)}</section>
 <section className="dashboard-grid"><article className="panel demand-panel"><div className="panel-head"><div><h3>Demand forecast</h3><p>Actual vs predicted unit demand</p></div><div className="range">{["24H","7D","30D"].map(x=><button key={x} onClick={()=>setRange(x)} className={range===x?"active":""}>{x}</button>)}</div></div><div className="legend"><span><i className="actual"/>Actual demand</span><span><i className="forecast"/>Forecast</span><b>Confidence: High</b></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.demand}><defs><linearGradient id="actual" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0b8f3c" stopOpacity=".25"/><stop offset="1" stopColor="#0b8f3c" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#edf0ea" vertical={false}/><XAxis dataKey="label" tick={{fontSize:11}} interval={3}/><YAxis tick={{fontSize:11}}/><Tooltip/><Area type="monotone" dataKey="actual" stroke="#0b8f3c" strokeWidth={2.5} fill="url(#actual)"/><Area type="monotone" dataKey="forecast" stroke="#e5b900" strokeDasharray="5 4" strokeWidth={2.5} fill="transparent"/></AreaChart></ResponsiveContainer></div><Link className="panel-deep-link" href="/demand">Open demand intelligence →</Link></article><article className="panel alerts"><div className="panel-head"><div><h3>Live alerts</h3><p>Signals requiring attention</p></div><Link href="/alerts">View all</Link></div>{data.alerts.map(a=><Link href="/alerts" className="alert-row" key={a.title}><span className={riskClass(a.severity)}><AlertTriangle size={15}/></span><div><strong>{a.title}</strong><p>{a.detail}</p></div><time>{a.time}</time></Link>)}</article></section>
 <section className="dashboard-grid lower"><article className="panel risk-table"><div className="panel-head"><div><h3>Products at risk</h3><p>Prioritized by expected stock-out impact</p></div><Link href="/inventory?risk=high">View inventory →</Link></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Store</th><th>Stock</th><th>Predicted</th><th>Time left</th><th>Risk</th><th>Action</th></tr></thead><tbody>{data.risks.slice(0,5).map(r=><tr key={r.sku}><td><Link href={`/products?q=${encodeURIComponent(r.product)}`}><strong>{r.product}</strong><small>{r.sku}</small></Link></td><td><Link href={`/stores?q=${encodeURIComponent(r.store)}`}>{r.store}</Link></td><td>{r.stock}</td><td>{r.demand}</td><td>{r.hours}h</td><td><span className={riskClass(r.risk)}>{r.risk}</span></td><td><button className="reorder" onClick={()=>showToast(`Reorder for ${r.reorder} units of ${r.product} created`)}>Reorder {r.reorder}</button></td></tr>)}</tbody></table></div></article><article className="panel store-health"><div className="panel-head"><div><h3>Store health</h3><p>Network performance</p></div><Link href="/stores">View all</Link></div>{data.stores.slice(0,5).map(s=><Link href={`/stores?q=${encodeURIComponent(s.name)}`} className="store-row" key={s.name}><div className="store-icon"><Store size={17}/></div><div><strong>{s.name}</strong><span>{s.orders.toLocaleString()} orders</span></div><div className="health"><span>{s.health}%</span><i><b style={{width:`${s.health}%`}}/></i></div></Link>)}</article></section>
 <footer><span>StockSense Intelligence Engine · Demo operational data</span><button onClick={()=>setStatusOpen(true)}><i/> All systems operational</button></footer>
 {statusOpen?<div className="modal-backdrop" onClick={()=>setStatusOpen(false)}><div className="status-modal" role="dialog" aria-modal="true" aria-labelledby="status-title" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Close system status" onClick={()=>setStatusOpen(false)}><X size={18}/></button><span className="status-pulse"/><h2 id="status-title">All systems operational</h2><p>Dashboard, intelligence engine, weather integration and API services are responding normally.</p><div className="status-list"><span>Dashboard API <b>Operational</b></span><span>Forecast engine <b>Ready</b></span><span>Weather API <b>Available</b></span><span>Last checked <b>Just now</b></span></div><Link href="/settings">Open system settings →</Link></div></div>:null}{toast?<div className="toast" role="status">{toast}</div>:null}
 </main></div>}
