"use client";
import { useState } from "react";
import { AlertTriangle, BarChart3, Bell, Boxes, Building2, ChevronDown, CircleGauge, CloudRain, Download, LayoutDashboard, PackageSearch, RefreshCw, Search, Settings, ShoppingCart, Sparkles, Store, Users } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DashboardData, Risk } from "@/lib/types";

const nav=[[LayoutDashboard,"Overview"],[BarChart3,"Demand Intelligence"],[Boxes,"Inventory"],[Store,"Stores"],[PackageSearch,"Products"],[ShoppingCart,"Orders"],[Sparkles,"Forecasts"],[CircleGauge,"Recommendations"],[Bell,"Alerts"],[BarChart3,"Analytics"],[Users,"Team"],[Settings,"Settings"]] as const;
const riskClass=(risk:Risk)=>`risk risk-${risk.toLowerCase()}`;
export default function Dashboard({initialData}:{initialData:DashboardData}){
 const [data,setData]=useState(initialData),[refreshing,setRefreshing]=useState(false),[range,setRange]=useState("24H"),[active,setActive]=useState("Overview");
 async function refresh(){setRefreshing(true);try{const r=await fetch("/api/refresh",{method:"POST"});if(!r.ok)throw new Error();setData(await r.json())}finally{setRefreshing(false)}}
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><strong>StockSense</strong><small>INTELLIGENCE OS</small></div></div><nav>{nav.map(([Icon,label])=><button key={label} className={active===label?"active":""} onClick={()=>setActive(label)}><Icon size={18}/><span>{label}</span>{label==="Alerts"&&<b>3</b>}</button>)}</nav><div className="upgrade"><Sparkles size={20}/><strong>Growth plan</strong><p>6 of 10 stores active</p><div><i style={{width:"60%"}}/></div><button>View usage</button></div><div className="account"><div className="avatar">AS</div><div><strong>Aarav Singh</strong><span>Owner</span></div><ChevronDown size={16}/></div></aside>
  <main><header><div><span className="eyebrow">OPERATIONS COMMAND CENTER</span><h1>Good morning, Aarav.</h1><p>Here’s what needs your attention across the network.</p></div><div className="header-actions"><label className="search"><Search size={17}/><input aria-label="Search" placeholder="Search products, stores..."/><kbd>⌘ K</kbd></label><button className="icon-btn" aria-label="Notifications"><Bell size={19}/><i/></button><button className="export"><Download size={17}/> Export</button></div></header>
  <section className="controlbar"><div className="live"><i/> LIVE INTELLIGENCE <span>Updated {refreshing?"refreshing…":"just now"}</span></div><div><button className="selector"><Building2 size={16}/> All stores <ChevronDown size={15}/></button><button className="refresh" onClick={refresh} disabled={refreshing}><RefreshCw size={16} className={refreshing?"spin":""}/>{refreshing?"Refreshing…":"Refresh data"}</button></div></section>
  <section className="intelligence"><div className="intelligence-title"><span><Sparkles size={18}/>TODAY’S INTELLIGENCE</span><small>AI-assisted operational summary</small></div><div className="insight-grid">{data.insights.map((x,i)=><div key={x}><b>{i+1}</b><p>{x}</p></div>)}</div></section>
  <section className="kpis">{data.kpis.map((k,i)=><article key={k.label}><div className={`kpi-icon ${k.tone}`}>{[Boxes,ShoppingCart,BarChart3,AlertTriangle,PackageSearch,CircleGauge].map((I,j)=>j===i?<I key={j} size={20}/>:null)}</div><p>{k.label}</p><h2>{k.value}</h2><span className={k.tone}>{k.delta}</span></article>)}</section>
  <section className="dashboard-grid"><article className="panel demand-panel"><div className="panel-head"><div><h3>Demand forecast</h3><p>Actual vs predicted unit demand</p></div><div className="range">{["24H","7D","30D"].map(x=><button key={x} onClick={()=>setRange(x)} className={range===x?"active":""}>{x}</button>)}</div></div><div className="legend"><span><i className="actual"/>Actual demand</span><span><i className="forecast"/>Forecast</span><b>Confidence: High</b></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.demand}><defs><linearGradient id="actual" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0b8f3c" stopOpacity=".25"/><stop offset="1" stopColor="#0b8f3c" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#edf0ea" vertical={false}/><XAxis dataKey="label" tick={{fontSize:11}} interval={3}/><YAxis tick={{fontSize:11}}/><Tooltip/><Area type="monotone" dataKey="actual" stroke="#0b8f3c" strokeWidth={2.5} fill="url(#actual)"/><Area type="monotone" dataKey="forecast" stroke="#e5b900" strokeDasharray="5 4" strokeWidth={2.5} fill="transparent"/></AreaChart></ResponsiveContainer></div></article>
  <article className="panel alerts"><div className="panel-head"><div><h3>Live alerts</h3><p>Signals requiring attention</p></div><button>View all</button></div>{data.alerts.map(a=><div className="alert-row" key={a.title}><span className={riskClass(a.severity)}><AlertTriangle size={15}/></span><div><strong>{a.title}</strong><p>{a.detail}</p></div><time>{a.time}</time></div>)}</article></section>
  <section className="dashboard-grid lower"><article className="panel risk-table"><div className="panel-head"><div><h3>Products at risk</h3><p>Prioritized by expected stock-out impact</p></div><button>View inventory →</button></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Store</th><th>Stock</th><th>Predicted</th><th>Time left</th><th>Risk</th><th>Action</th></tr></thead><tbody>{data.risks.slice(0,5).map(r=><tr key={r.sku}><td><strong>{r.product}</strong><small>{r.sku}</small></td><td>{r.store}</td><td>{r.stock}</td><td>{r.demand}</td><td>{r.hours}h</td><td><span className={riskClass(r.risk)}>{r.risk}</span></td><td><button className="reorder">Reorder {r.reorder}</button></td></tr>)}</tbody></table></div></article><article className="panel store-health"><div className="panel-head"><div><h3>Store health</h3><p>Network performance</p></div><button>View all</button></div>{data.stores.slice(0,5).map(s=><div className="store-row" key={s.name}><div className="store-icon"><Store size={17}/></div><div><strong>{s.name}</strong><span>{s.orders.toLocaleString()} orders</span></div><div className="health"><span>{s.health}%</span><i><b style={{width:`${s.health}%`}}/></i></div></div>)}</article></section>
  <footer><span>StockSense Intelligence Engine · Demo operational data</span><span><i/> All systems operational</span></footer>
 </main></div>
}
